### ISSUE TITLE
CloudWatchLogger 0.3.0 is not compatible

### ISSUE THREAD

**Issue by slemrmartin** [ManageIQ/manageiq-loggers#25]
1) version 0.2.1 defaults region to 'us-east-1' but 0.3.0 requires `AWS_REGION` ENV.
2) version 0.3.0 expects that formatter returns hash instead of message (https://github.com/zshannon/cloudwatchlogger/issues/16)

**Comment by slemrmartin** [comment]
Hi @agrare this is probably related also to MiQ

**Comment by slemrmartin** [comment]
https://github.com/zshannon/cloudwatchlogger/pull/17 should fix it

**Comment by Fryguy** [comment]
Closing after #81
