### ISSUE TITLE
ContainerLogger STDOUT is not synced

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-loggers#26]
Should we set STDOUT.sync on the container logger if an io is not passed in?  I am observing that the log output is not synced, and ends up getting chunked to the output.  I could be wrong, as it's hard to tell.

**Comment by agrare** [comment]
:+1: we did this in each topo bin script for this exact reason (e.g. https://github.com/RedHatInsights/topological_inventory-amazon/blob/master/bin/amazon-collector#L6)

**Comment by Fryguy** [comment]
Seems it already is 😕 - something else must be going on

https://github.com/ManageIQ/manageiq-loggers/blob/241ebecd7930a481733fcbea93ebde92f4226acc/lib/manageiq/loggers/container.rb#L5
