### ISSUE TITLE
For micro services using the container logger log 3scale request_id

### ISSUE THREAD

**Issue by mkanoor** [ManageIQ/manageiq-loggers#6]
3scale creates a request id for every API call. When we make a Provision request we need to collect logs from all of our services (catalog, approval, topology) for that request. This requires logging the request id if it exists.

https://github.com/ManageIQ/manageiq-loggers/blob/606f727605b8577b9a1c5b3ee676dbfd2bc03947/lib/manageiq/loggers/container.rb#L36

**Comment by mkanoor** [comment]
@carbonin @Fryguy 
Thoughts?

**Comment by mkanoor** [comment]
```
def request_id
     ManageIQ::API::Common::Request.current&.request_id || "unknown"
 end
```

**Comment by carbonin** [comment]
If we want to avoid a dependency directly on the gem maybe we could do something like:
```ruby
Thread.current[:current_request]&.request_id || "unknown"
```

But I don't know if we're considering that thread local part of the gem's "API" ...

**Comment by carbonin** [comment]
:scream: @miq-bot is sentient again @Fryguy help!

**Comment by mkanoor** [comment]
The problem with using the Rails.logger.request_id is we would be doing that before every log message. Since these requests are frequent and short lived and keep changing with every API call.

**Comment by carbonin** [comment]
@mkanoor The proc implementation is exactly the same as what you suggested. We would still re-evaluate the request_id on each log call, it's just that the user of the logger can tell the gem how to find the request id rather than baking that detail into the gem.

You would call `Rails.logger.request_id=` in an initializer at the same time that you configure the logger.

I like the idea.

**Comment by mkanoor** [comment]
@carbonin Didn't realize it just gets done once and the method gets evaluated every time. So would this happen here in the common gem here
https://github.com/ManageIQ/manageiq-api-common/blob/810d63e3d983d765e064438bf55c942ff237acf7/lib/manageiq/api/common/logging.rb#L8

**Comment by carbonin** [comment]
Yup, that looks like it would be a good place for it if we want to assume that every user of the `Logging` module is also using the `Request` handling one.
